name: CICD-Prod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Deploy
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          source_dir: "./src"
          container_name: "$web"
          connection_string: ${{ secrets.azureprodconnectingstring }}
          overwrite: "true"
